const fs = require('fs');
const path = require('path');

const SRC_INDEX = path.resolve(__dirname, '..', 'src', 'index.js');
const SRC_CONTENT = path.resolve(__dirname, '..', 'src', 'content.json');
const OUT_DIR = path.resolve(__dirname, '..', 'dist');
const OUT_FILE = path.join(OUT_DIR, 'worker.inlined.js');

function main() {
  if (!fs.existsSync(SRC_INDEX)) {
    console.error('src/index.js not found. Run from project root.');
    process.exit(1);
  }
  if (!fs.existsSync(SRC_CONTENT)) {
    console.error('src/content.json not found. Run `npm run build-content` first.');
    process.exit(1);
  }
  const script = fs.readFileSync(SRC_INDEX, 'utf8');
  const content = fs.readFileSync(SRC_CONTENT, 'utf8');

  // Remove import line that loads content.json
  const outScript = script.replace(/import\s+content\s+from\s+['"][\.\/]*content.json['"].*;?\s*/m, '');

  const header = `// Worker script with inlined content.json\n// Generated by tools/inline-worker.js\nconst content = ${content};\n\n`;

  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT_FILE, header + outScript, 'utf8');
  console.log('Wrote inlined worker to', OUT_FILE);
}

main();
